# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-16 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YourName', models.CharField(max_length=40)),
                ('YourEmail', models.EmailField(max_length=254)),
                ('YourMessage', models.TextField()),
            ],
        ),
    ]
