# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-17 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Studentapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddstudentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=24)),
                ('gender', models.CharField(max_length=30)),
                ('phno', models.IntegerField()),
                ('dob', models.IntegerField()),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('course', models.CharField(max_length=30)),
                ('add', models.TextField(max_length=40)),
            ],
        ),
    ]
