# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-17 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Studentapp', '0002_addstudentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addstudentmodel',
            name='add',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='addstudentmodel',
            name='dob',
            field=models.DateField(),
        ),
    ]
