# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-05 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgupload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgmodel',
            name='flag',
            field=models.CharField(choices=[('0', '0'), ('1', '1')], default=0, max_length=2, null=True),
        ),
    ]
